name: Create Zip Archive

on:
  push:
    branches:
      - main

jobs:
  create-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Zip Archive
        run: |
          # Create a "scalewithus" folder inside the zip
          mkdir -p scalewithus
          
          # Copy all files from the main branch to the "scalewithus" folder
          cp -r ./* scalewithus/
          
          # Create a zip archive named "archive.zip" containing the "scalewithus" folder
          zip -r archive.zip scalewithus/
          
          # Optionally, you can move the archive to a specific location or upload it as an artifact
          mv archive.zip path/to/destination/ # Move the archive to a specific location
          echo "::set-output name=zip-path::path/to/destination/archive.zip" # Set an output variable to pass the zip file path to the next step
        working-directory: ${{ github.workspace }}

      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v2
        with:
          name: scalewithus-zip
          path: ${{ steps.create-zip.outputs.zip-path }}