name: Create Zip Archive

on:
  push:
    branches:
      - main

jobs:
  create-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Zip Archive
        run: |
          # Create a "scalewithus" folder inside the zip
          mkdir -p /tmp/scalewithus
          
          # Copy all files from the main branch to the "scalewithus" folder
          cp -r ./* /tmp/scalewithus/
          
          # Create a zip archive named "scalewithus.zip" containing the "scalewithus" folder
          cd /tmp/
          zip -r scalewithus.zip /tmp/scalewithus
          
          # Optionally, you can move the archive to a specific location or upload it as an artifact
          # mv scalewithus.zip /tmp/ # Move the archive to a specific location
          # echo "::set-output name=zip-path::/tmp/scalewithus/archive.zip" # Set an output variable to pass the zip file path to the next step
        working-directory: /tmp/

      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v2
        with:
          name: scalewithus.zip
          path:  scalewithus